# Generated by cmake2bazel.
# Any issue please report to https://open.codehub.huawei.com/innersource/hazel/toolkits/issues
# Caesar Task Force@Data Storage Product Line
GLOBAL_COPTS = []
GLOBAL_LOCAL_DEFINES = []
GLOBAL_LINKOPTS = []
