/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
#ifndef MEMFABRIC_HYBRID_MMC_PTRACER_H
#define MEMFABRIC_HYBRID_MMC_PTRACER_H

#include "ptracer.h"

enum TP_MMC_MOD {
    TP_MMC_START = PTRACER_ID(1, 0U),
    TP_MMC_PY_PUT,
    TP_MMC_PY_BATCH_PUT,
    TP_MMC_PY_PUT_LAYERS,
    TP_MMC_PY_PUT_LAYERS_2D,
    TP_MMC_PY_BATCH_PUT_LAYERS,
    TP_MMC_PY_BATCH_PUT_LAYERS_2D,
    TP_MMC_PY_GET,
    TP_MMC_PY_BATCH_GET,
    TP_MMC_PY_GET_LAYERS,
    TP_MMC_PY_GET_LAYERS_2D,
    TP_MMC_PY_BATCH_GET_LAYERS,
    TP_MMC_PY_BATCH_GET_LAYERS_2D,
    TP_MMC_PY_UPDATE,
    TP_MMC_PY_BATCH_UPDATE,
    TP_MMC_PY_REMOVE,
    TP_MMC_PY_BATCH_REMOVE,
    TP_MMC_PY_EXIST,
    TP_MMC_PY_BATCH_EXIST,
    TP_MMC_PY_QUERY,
    TP_MMC_PY_BATCH_QUERY,

    TP_MMC_LOCAL_PUT,
    TP_MMC_LOCAL_BATCH_PUT,
    TP_MMC_LOCAL_GET,
    TP_MMC_LOCAL_BATCH_GET,
    TP_MMC_LOCAL_UPDATE,
    TP_MMC_LOCAL_BATCH_UPDATE,
    TP_MMC_LOCAL_REMOVE,
    TP_MMC_LOCAL_BATCH_REMOVE,

    TP_MMC_META_PUT,
    TP_MMC_META_BATCH_PUT,
    TP_MMC_META_GET,
    TP_MMC_META_BATCH_GET,
    TP_MMC_META_UPDATE,
    TP_MMC_META_BATCH_UPDATE,
    TP_MMC_META_REMOVE,
    TP_MMC_META_BATCH_REMOVE,
    TP_MMC_META_EXIST,
    TP_MMC_META_BATCH_EXIST,
    TP_MMC_META_QUERY,
    TP_MMC_META_BATCH_QUERY,
    TP_MMC_META_BM_REGISTER,
    TP_MMC_META_BM_UNREGISTER,
    TP_MMC_META_CLEAR_RESOURCE,

    TP_SMEM_BM_PUT,
    TP_SMEM_BM_PUT_2D,
    TP_SMEM_BM_GET,
    TP_SMEM_BM_GET_2D,
};

#endif