/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */
#ifndef MF_HYBRID_HYBM_PTRACER_H
#define MF_HYBRID_HYBM_PTRACER_H

#include "ptracer.h"

enum MF_HYBM_MOD {
    TP_HYBM_START = PTRACER_ID(0, 0U),
    TP_HYBM_SDMA_LH_TO_GH,
    TP_HYBM_SDMA_LH_TO_GD,
    TP_HYBM_SDMA_LD_TO_GH,
    TP_HYBM_SDMA_LD_TO_GD,

    TP_HYBM_SDMA_GH_TO_LD,
    TP_HYBM_SDMA_GH_TO_LH,
    TP_HYBM_SDMA_GD_TO_LD,
    TP_HYBM_SDMA_GD_TO_LH,

    TP_HYBM_SDMA_GH_TO_GH,
    TP_HYBM_SDMA_GH_TO_GD,
    TP_HYBM_SDMA_GD_TO_GD,
    TP_HYBM_SDMA_GD_TO_GH,

    TP_HYBM_RDMA_LH_TO_GH,
    TP_HYBM_RDMA_LH_TO_GD,
    TP_HYBM_RDMA_LD_TO_GH,
    TP_HYBM_RDMA_LD_TO_GD,

    TP_HYBM_RDMA_GH_TO_LD,
    TP_HYBM_RDMA_GH_TO_LH,
    TP_HYBM_RDMA_GD_TO_LD,
    TP_HYBM_RDMA_GD_TO_LH,

    TP_HYBM_RDMA_GH_TO_GH,
    TP_HYBM_RDMA_GH_TO_GD,
    TP_HYBM_RDMA_GD_TO_GD,
    TP_HYBM_RDMA_GD_TO_GH,
};

#endif  // MF_HYBRID_HYBM_PTRACER_H