# meta命名空间定义，用于memcache所有资源，包括：meta-pods，local-pods，ServiceAccount，role，RoleBinding，Lease和ClusterIP
apiVersion: v1
kind: Namespace
metadata:
  name: ns-memcache # Lease、Service和StatefulSet三种资源，都必须采用该 namespace

---
# 服务账号定义（与pod及lease相同命名空间）
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-memcache
  namespace: ns-memcache # 位于 ns-memcache namespace中

---
# 角色定义（命名空间内）
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-memcache
  namespace: ns-memcache
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: [""]  # 核心 API 组（Pod 属于此组）
    resources: ["pods"]
    verbs: ["get", "patch"]  # 仅需查询（get）和部分更新（patch）权限

---
# 角色绑定（与pod及lease相同命名空间）
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-memcache
  namespace: ns-memcache
subjects:
  - kind: ServiceAccount
    name: account-memcache
    namespace: ns-memcache
roleRef:
  kind: Role
  name: role-memcache
  apiGroup: rbac.authorization.k8s.io
